# Generated by Django 3.0.8 on 2020-07-14 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Email', '0005_auto_20200713_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='mail',
            name='label',
            field=models.CharField(blank=True, choices=[('SP', 'Support'), ('AS', 'Assignment'), ('EX', 'Examination'), ('PR', 'Practical')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mail_requests_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mail',
            name='subject',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
