# Generated by Django 3.0.8 on 2020-07-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0008_auto_20200714_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='mail_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
