# Generated by Django 3.0.8 on 2020-07-15 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0009_mail_mail_viewed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='spam',
            new_name='mail_spam',
        ),
        migrations.RenameField(
            model_name='mail',
            old_name='starred',
            new_name='mail_starred',
        ),
    ]
