# Generated by Django 3.0.8 on 2020-07-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0010_auto_20200715_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='mail_draft',
            field=models.BooleanField(default=False),
        ),
    ]
