# Generated by Django 3.0.8 on 2020-07-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0011_mail_mail_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('teachers', models.ManyToManyField(to='Email.Teacher')),
            ],
        ),
    ]
