# Generated by Django 3.0.8 on 2020-07-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0012_student_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(blank=True, null=True, to='Email.Teacher'),
        ),
    ]
