# Generated by Django 3.0.8 on 2020-07-15 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0014_auto_20200715_1206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
