# Generated by Django 3.0.8 on 2020-07-17 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0015_auto_20200715_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='reply_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Email.Mail'),
        ),
    ]
