# Generated by Django 3.0.8 on 2020-07-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0017_auto_20200717_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='label',
            field=models.CharField(blank=True, choices=[('SP', 'Support'), ('AS', 'Assignment'), ('EX', 'Examination'), ('PR', 'Practical')], max_length=2, null=True),
        ),
    ]
